POST {{baseUrl}}invitation/AddInvite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IktvZmkgR3lhc2kiLCJuYW1laWQiOiIwMmEwZTMyZi0wZjc4LTRlZWEtOTg0YS05NmYyNWFiMmU4ZWQiLCJmYW1pbHlfbmFtZSI6Ikd5YXNpIiwiSW1hZ2VVcmwiOiIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9tb2JpbGVwaG9uZSI6IjA1NTc4MzMyMTYiLCJyb2xlIjoiQXJ0aXNhbiIsImVtYWlsIjoiIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3RyZWV0YWRkcmVzcyI6IiIsIm5iZiI6MTY2NTY3NTQ1NiwiZXhwIjoxNjY1Njc5MDU2LCJpYXQiOjE2NjU2NzU0NTYsImlzcyI6IkFtcEF1dGhlbnRpY2F0aW9uU3lzdGVtIiwiYXVkIjoiQW1wV2ViUGxhdGZvcm0ifQ.YiRsnd-9l0nGF59oi6SSXsHbJUcdr20KdHaavN3-abI

{
  "invitedPhone": "0558247380",
  "type": 4
}

###
